### ISSUE TITLE
avoid querying inventory history

### ISSUE THREAD

**Issue by cgsdev0** [denbeigh2000/csgotothecasino#1]
https://github.com/denbeigh2000/csgotothecasino/blob/68342e9f75ab9ab5097b89fc304abab473cd4f36/casino/steam/src/lib.rs#L188-L194

I think we should drop this functionality - it's likely what hit the API rate limit so quickly

in theory, we can just pull the actual inventory to get the latest few items, and see if there's anything new in that result

I think that will give us a lot more headroom, albeit at the cost of some information (e.g. whether something was unboxed or crafted)

**Comment by denbeigh2000** [comment]
Looks like steam has an open JSON inventory API that supports a `start_assetid` field - should be fairly easy to swap to that api and trivially check the new items, but whether that actually addresses our rate-limiting issue remains to be seen.

**Comment by denbeigh2000** [comment]
This should be addressed by 19fcc7d..807b5f, ty for the suggestion!
